### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by hugopassos**

### CODE REVIEW

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
Hi @hugopassos good job on this one, everything looks good but the header is off, something always get us :smile: . Anyways, the header currently occupies a very large portion of the screen vertically, please fix that. This seems to be the only issue 
Please submit for re-review when you are done. :pray:

**Comment by hugopassos** [comment]
> Hi @hugopassos good job on this one, everything looks good but the header is off, something always get us 😄 . Anyways, the header currently occupies a very large portion of the screen vertically, please fix that. This seems to be the only issue
> Please submit for re-review when you are done. 🙏

Could you clarify what's wrong with the header?

**Comment by Oghenebrume50** [comment]
Hi @hugopassos this is the screenshot of your latest fix, from this branch, I believe the screenshot above is from the master branch. so your lates fix is buggy. I sent you the link on slack

**Review by Oghenebrume50 — APPROVED** [review]
Looks good after seeing the preview from your end, not sure why it is broken for me though. But you can merge this now.

**Comment by hugopassos** [comment]
Thank you. Just to mention, I asked my coding partner to check if it is working for him and it is as well.

**Pull request merged**
